sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tMuiT6ULZd1jLZsACC3
    access-key-secret: bKK4IdzzsAVvczXF9eigjYlKI5PJeI
    bucket-name: firmament-takeout
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx7adf2482a6cc37eb
    secret: 284def6c7ff4bc0d18a2f03cd13d4678